### ISSUE TITLE
S4: Musiktrackauswahl modular gestallten (Interface)

### ISSUE THREAD

**Issue by kdsystem1337** [settlers-united/orga#58]
Erstellung eines Interfaces in dem die Musiktrackzuordnung der S4 Tracks (inkl. optionaler s3 musik) frei ausgewählt werden kann.

```
Theme              Music          Volk
Track02.mp3    Track02.ogg   Römer 1
Track03.mp3    Track03.ogg   Römer 2
Track09.mp3    Track04.ogg   Asiaten 2
Track10.mp3    Track05.ogg   Asiaten 3
Track05.mp3    Track06.ogg   Ägypter 1
Track06.mp3    Track07.ogg   Ägypter 2
Track15.mp3    Track08.ogg   Amazonen 3
Track13.mp3    Track09.ogg   Amazonen 1
Track14.mp3    Track10.ogg   Amazonen 2
Track11.mp3    Track11.ogg   Andere 1
Track04.mp3    Track12.ogg   Römer 3
Track08.mp3    Track13.ogg   Asiaten 1
Track07.mp3    Track14.ogg   Ägypter 3
Track12.mp3    Track15.ogg   Andere 2
```

**Comment by TheKingJo** [comment]
- So frei wie möglich, aber nur so kompliziert wie auch machbar
- Konfigurierbar:
Jedes S4 Volk : Settle/Fight/Sea-Kategorie : Jede S3/4 Musik -> 3-dim-array

- Zwischenspeichern des Arrays in lesbarem Dateiformat für Presets; "Playlist"-Austausch zwischen Spielern
- King Jo teilt S3 Soundtracks in pseudo-settle/fight/sea ein. (Because let's not go to 4-dim :D)

**Comment by kdsystem1337** [comment]
Aufgrund des niedrigen Interesses wird zunächst nur die Option Benutzerdefinierte SoundTracks Konfigs zu verwenden implementiert (zu finden unter den Music Einstellungen in SU sowie in der Datei "\Config\SoundTracks_CUSTOM.cfg")
